export const APPOINTMENT_CREATE_RESET = 'APPOINTMENT_CREATE_RESET';
export const APPOINTMENT_CREATE_REQUEST = 'APPOINTMENT_CREATE_REQUEST';
export const APPOINTMENT_CREATE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS';
export const APPOINTMENT_CREATE_FAIL = 'APPOINTMENT_CREATE_FAIL';

export const APPOINTMENT_DETAILS_REQUEST = 'APPOINTMENT_DETAILS_REQUEST';
export const APPOINTMENT_DETAILS_SUCCESS = 'APPOINTMENT_DETAILS_SUCCESS';
export const APPOINTMENT_DETAILS_FAIL = 'APPOINTMENT_DETAILS_FAIL';

export const APPOINTMENT_MINE_LIST_REQUEST = 'APPOINTMENT_MINE_LIST_REQUEST';
export const APPOINTMENT_MINE_LIST_SUCCESS = 'APPOINTMENT_MINE_LIST_SUCCESS';
export const APPOINTMENT_MINE_LIST_FAIL = 'APPOINTMENT_MINE_LIST_FAIL';

export const APPOINTMENT_SUMMARY_REQUEST = 'APPOINTMENT_SUMMARY_REQUEST';
export const APPOINTMENT_SUMMARY_SUCCESS = 'APPOINTMENT_SUMMARY_SUCCESS';
export const APPOINTMENT_SUMMARY_FAIL = 'APPOINTMENT_SUMMARY_FAIL';

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST';
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS';
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL';



export const APPOINTMENT_DELIVER_REQUEST = 'APPOINTMENT_DELIVER_REQUEST';
export const APPOINTMENT_DELIVER_SUCCESS = 'APPOINTMENT_DELIVER_SUCCESS';
export const APPOINTMENT_DELIVER_FAIL = 'APPOINTMENT_DELIVER_FAIL';
export const APPOINTMENT_DELIVER_RESET = 'APPOINTMENT_DELIVER_RESET';

export const APPOINTMENT_DELETE_REQUEST = 'APPOINTMENT_DELETE_REQUEST';
export const APPOINTMENT_DELETE_SUCCESS = 'APPOINTMENT_DELETE_SUCCESS';
export const APPOINTMENT_DELETE_FAIL = 'APPOINTMENT_DELETE_FAIL';
