export const BOOKING_ADD_ITEM = 'BOOKING_ADD_ITEM';
export const BOOKING_ADD_ITEM_FAIL = 'BOOKING_ADD_ITEM_FAIL';
export const BOOKING_EMPTY = 'BOOKING_EMPTY';
export const BOOKING_REMOVE_ITEM = 'BOOKING_REMOVE_ITEM';
export const BOOKING_SAVE_SHIPPING_ADDRESSA = 'BOOKING_SAVE_SHIPPING_ADDRESSA';
export const BOOKING_SAVE_PAYMENT_METHOD = 'BOOKING_SAVE_PAYMENT_METHOD';
