export const DOCPROFILE_LIST_REQUEST = 'DOCPROFILE_LIST_REQUEST';
export const DOCPROFILE_LIST_SUCCESS = 'DOCPROFILE_LIST_SUCCESS';
export const DOCPROFILE_LIST_FAIL = 'DOCPROFILE_LIST_FAIL';

export const DOCPROFILE_CREATE_REQUEST = 'DOCPROFILE_CREATE_REQUEST';
export const DOCPROFILE_CREATE_SUCCESS = 'DOCPROFILE_CREATE_SUCCESS';
export const DOCPROFILE_CREATE_FAIL = 'DOCPROFILE_CREATE_FAIL';
export const DOCPROFILE_CREATE_RESET = 'DOCPROFILE_CREATE_RESET';

export const DOCPROFILE_DETAILS_REQUEST = 'DOCPROFILE_DETAILS_REQUEST';
export const DOCPROFILE_DETAILS_SUCCESS = 'DOCPROFILE_DETAILS_SUCCESS';
export const DOCPROFILE_DETAILS_FAIL = 'DOCPROFILE_DETAILS_FAIL';
export const DOCPROFILE_DETAILS_RESET = 'DOCPROFILE_DETAILS_RESET';

export const DOCPROFILE_UPDATE_REQUEST = 'DOCPROFILE_UPDATE_REQUEST';
export const DOCPROFILE_UPDATE_SUCCESS = 'DOCPROFILE_UPDATE_SUCCESS';
export const DOCPROFILE_UPDATE_FAIL = 'DOCPROFILE_UPDATE_FAIL';
export const DOCPROFILE_UPDATE_RESET = 'DOCPROFILE_UPDATE_RESET';

export const DOCPROFILE_DELETE_REQUEST = 'DOCPROFILE_DELETE_REQUEST';
export const DOCPROFILE_DELETE_SUCCESS = 'DOCPROFILE_DELETE_SUCCESS';
export const DOCPROFILE_DELETE_FAIL = 'DOCPROFILE_DELETE_FAIL';

export const DOCPROFILE_REVIEW_SAVE_REQUEST = 'DOCPROFILE_REVIEW_SAVE_REQUEST';
export const DOCPROFILE_REVIEW_SAVE_SUCCESS = 'DOCPROFILE_REVIEW_SAVE_SUCCESS';
export const DOCPROFILE_REVIEW_SAVE_FAIL = 'DOCPROFILE_REVIEW_SAVE_FAIL';
export const DOCPROFILE_REVIEW_SAVE_RESET = 'DOCPROFILE_REVIEW_SAVE_RESET';

export const DOCPROFILE_CATEGORY_LIST_REQUEST = 'DOCPROFILE_CATEGORY_LIST_REQUEST';
export const DOCPROFILE_CATEGORY_LIST_SUCCESS = 'DOCPROFILE_CATEGORY_LIST_SUCCESS';
export const DOCPROFILE_CATEGORY_LIST_FAIL = 'DOCPROFILE_CATEGORY_LIST_FAIL';
