export const LOSTPET_LIST_REQUEST = 'LOSTPET_LIST_REQUEST';
export const LOSTPET_LIST_SUCCESS = 'LOSTPET_LIST_SUCCESS';
export const LOSTPET_LIST_FAIL = 'LOSTPET_LIST_FAIL';

export const LOSTPET_CREATE_REQUEST = 'LOSTPET_CREATE_REQUEST';
export const LOSTPET_CREATE_SUCCESS = 'LOSTPET_CREATE_SUCCESS';
export const LOSTPET_CREATE_FAIL = 'LOSTPET_CREATE_FAIL';
export const LOSTPET_CREATE_RESET = 'LOSTPET_CREATE_RESET';

export const LOSTPET_DETAILS_REQUEST = 'LOSTPET_DETAILS_REQUEST';
export const LOSTPET_DETAILS_SUCCESS = 'LOSTPET_DETAILS_SUCCESS';
export const LOSTPET_DETAILS_FAIL = 'LOSTPET_DETAILS_FAIL';
export const LOSTPET_DETAILS_RESET = 'LOSTPET_DETAILS_RESET';

export const LOSTPET_UPDATE_REQUEST = 'LOSTPET_UPDATE_REQUEST';
export const LOSTPET_UPDATE_SUCCESS = 'LOSTPET_UPDATE_SUCCESS';
export const LOSTPET_UPDATE_FAIL = 'LOSTPET_UPDATE_FAIL';
export const LOSTPET_UPDATE_RESET = 'LOSTPET_UPDATE_RESET';

export const LOSTPET_DELETE_REQUEST = 'LOSTPET_DELETE_REQUEST';
export const LOSTPET_DELETE_SUCCESS = 'LOSTPET_DELETE_SUCCESS';
export const LOSTPET_DELETE_FAIL = 'LOSTPET_DELETE_FAIL';

export const LOSTPET_REVIEW_SAVE_REQUEST = 'LOSTPET_REVIEW_SAVE_REQUEST';
export const LOSTPET_REVIEW_SAVE_SUCCESS = 'LOSTPET_REVIEW_SAVE_SUCCESS';
export const LOSTPET_REVIEW_SAVE_FAIL = 'LOSTPET_REVIEW_SAVE_FAIL';
export const LOSTPET_REVIEW_SAVE_RESET = 'LOSTPET_REVIEW_SAVE_RESET';

export const LOSTPET_CATEGORY_LIST_REQUEST = 'LOSTPET_CATEGORY_LIST_REQUEST';
export const LOSTPET_CATEGORY_LIST_SUCCESS = 'LOSTPET_CATEGORY_LIST_SUCCESS';
export const LOSTPET_CATEGORY_LIST_FAIL = 'LOSTPET_CATEGORY_LIST_FAIL';
